apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: dataengineeringworkshop.azurecr.io/fastapi:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
